In [14]:
# import libraries

import csv
import pandas as pd

In [15]:
# source 1, only sales data based on platform, genre, and publisher

url_1 = "data/csv/sales_data.csv"
sales_data = pd.read_csv(url_1)
sales_data = sales_data.dropna()
sales_data.to_csv("data/csv/sales_data_clean.csv", index= False, header = True)

sales_data

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [16]:
# source : sales data+ rating and critic scores:

url_2 = "data/csv/rating_sale.csv"
rating_sale = pd.read_csv(url_2)
rating_sale = rating_sale.dropna()
rating_sale.to_csv("data/csv/rating_sale_clean.csv", index= False, header = True)
rating_sale

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
6,New Super Mario Bros.,DS,2006.0,Platform,Nintendo,11.28,9.14,6.50,2.88,29.80,89.0,65.0,8.5,431.0,Nintendo,E
7,Wii Play,Wii,2006.0,Misc,Nintendo,13.96,9.18,2.93,2.84,28.92,58.0,41.0,6.6,129.0,Nintendo,E
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16667,E.T. The Extra-Terrestrial,GBA,2001.0,Action,NewKidCo,0.01,0.00,0.00,0.00,0.01,46.0,4.0,2.4,21.0,Fluid Studios,E
16677,Mortal Kombat: Deadly Alliance,GBA,2002.0,Fighting,Midway Games,0.01,0.00,0.00,0.00,0.01,81.0,12.0,8.8,9.0,Criterion Games,M
16696,Metal Gear Solid V: Ground Zeroes,PC,2014.0,Action,Konami Digital Entertainment,0.00,0.01,0.00,0.00,0.01,80.0,20.0,7.6,412.0,Kojima Productions,M
16700,Breach,PC,2011.0,Shooter,Destineer,0.01,0.00,0.00,0.00,0.01,61.0,12.0,5.8,43.0,Atomic Games,T
16706,STORM: Frontline Nation,PC,2011.0,Strategy,Unknown,0.00,0.01,0.00,0.00,0.01,60.0,12.0,7.2,13.0,SimBin,E10+

In [17]:
# source 3: scraping whatoplay: "https://whatoplay.com/best?sort-by=gamer_score" => game score, play score, critic score

url_3 = "data/csv/scraping_result.csv"

whatoplay_data = pd.read_csv(url_3)

whatoplay_data = whatoplay_data.dropna()
whatoplay_data.to_csv("data/csv/whatoplay_data_clean.csv")

whatoplay_data

,Name,Platform,Play Score,Game Score,Critic Score
0,Grand Theft Auto V,Xbox 360,9.64,9.97,9.30
1,Naruto Shippuden: Ultimate Ninja Storm 3,Xbox 360,8.68,9.91,7.45
2,A Short Hike,PC,8.98,9.84,8.13
3,Final Fantasy VII,PS4,8.87,9.84,7.89
4,The Room Two,Android,9.23,9.80,8.67
...,...,...,...,...,...
11355,"Warhammer 40,000: Dawn of War III",PC,6.30,4.72,7.88
11356,Splendor,iOS,6.43,4.72,8.14
11357,FIFA 18,PC,6.29,4.19,8.39
11358,NBA 2K19,PC,6.07,4.02,8.12
11359,NBA 2K18,Xbox One,6.03,3.80,8.27

In [18]:
total_data = pd.merge(rating_sale, whatoplay_data, how = "inner", on=["Name", "Platform"] )

total_data

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating,Play Score,Game Score,Critic Score
0,Grand Theft Auto V,PS3,2013.0,Action,Take-Two Interactive,7.02,9.09,0.98,3.96,21.04,97.0,50.0,8.2,3994.0,Rockstar North,M,9.29,9.34,9.24
1,Call of Duty: Black Ops II,PS3,2012.0,Shooter,Activision,4.99,5.73,0.65,2.42,13.79,83.0,21.0,5.3,922.0,Treyarch,M,7.73,7.52,7.95
2,Call of Duty: Modern Warfare 3,PS3,2011.0,Shooter,Activision,5.54,5.73,0.49,1.57,13.32,88.0,39.0,3.2,5234.0,"Infinity Ward, Sledgehammer Games",M,8.00,7.56,8.44
3,Mario Kart 7,3DS,2011.0,Racing,Nintendo,5.03,4.02,2.69,0.91,12.66,85.0,73.0,8.2,632.0,"Retro Studios, Entertainment Analysis & Develo...",E,9.09,9.77,8.41
4,Call of Duty: Black Ops,PS3,2010.0,Shooter,Activision,5.99,4.37,0.48,1.79,12.63,88.0,58.0,6.4,1094.0,Treyarch,M,8.16,7.91,8.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1190,Alone in the Dark,PC,2008.0,Adventure,Atari,0.00,0.01,0.00,0.00,0.01,55.0,19.0,5.7,148.0,Eden Studios,M,6.02,5.66,6.38
1191,Clive Barker's Jericho,PC,2007.0,Shooter,Codemasters,0.00,0.01,0.00,0.00,0.01,63.0,25.0,7.5,218.0,"Mercury Steam, Alchemic Productions",M,7.04,7.38,6.71
1192,Transformers: Fall of Cybertron,PC,2012.0,Action,Activision,0.01,0.00,0.00,0.00,0.01,78.0,13.0,7.9,121.0,"High Moon Studios, Mercenary Technologies",T,8.39,8.98,7.80
1193,Trine,PC,2009.0,Action,Nobilis,0.00,0.01,0.00,0.00,0.01,80.0,50.0,8.2,488.0,"Frozenbyte, Inc.",E10+,8.61,9.34,7.87
1194,Metal Gear Solid V: Ground Zeroes,PC,2014.0,Action,Konami Digital Entertainment,0.00,0.01,0.00,0.00,0.01,80.0,20.0,7.6,412.0,Kojima Productions,M,7.98,8.16,7.79

In [19]:
# Store the final table as csv file

total_data.to_csv("data/csv/master_table_clean.csv", index= False, header = True)

In [21]:
# convert csv to jason format

total_data.to_json ("data/json/master_table.json")
rating_sale.to_json ("data/json/rating_sale.json")
sales_data.to_json("data/json/sales_data.json")
whatoplay_data.to_json ("data/json/whatoplay_data.json")